title: Using DOM functions
hero_image: images/banner.png
description: Using DOM functions in JavaScript
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Using DOM functions
 
