---
title: Utiliser les fonctions DOM
hero_image: images/banner.png
description: Utiliser les fonctions DOM en JavaScript
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Utiliser les fonctions DOM
